'开始
@startuml
'用于控制显示权限修饰符icon
'skinparam classAttributeIconSize 0

'一 实现
'实现写法1
class MyXListener implements XListener{
+  public成员
-  private成员
#  protected成员
~  package成员

+  public方法()
-  private方法()
#  {static} protected静态方法()
~ {abstract}  抽象package方法()
}
'实现写法2
XListener02 "注释01" <|.. "注释02" MyXListener02 :注释03
'权限修饰符
MyXListener02 : +  public成员
MyXListener02 : -  private成员
MyXListener02 : #  protected成员
MyXListener02 : ~  package成员
'MyXListener02 : +  public方法()
MyXListener02 : -  private方法()
MyXListener02 : #  protected方法()
MyXListener02 : ~  package方法()


'二 继承
'继成写法
Class ExClass01 extends MyXListener{
}
'继承写法02
MyXListener02<|--  ExClass02


note "自定义分割线" as ss
ss..ClassA
class ClassA{
+ 成员一
+ 成员二
+ 成员三
'实线分割线
==
 - 方法一 ()
 - 方法二 ()
 - 方法三 ()
'虚线分割线
..
 - 方法四 ()
 - 方法五 ()
 - 方法五 ()
 - 方法五 ()
.. 虚线 ..
-- 单实线 --
== 双实线 ==

 - 方法五 ()
 - 方法五 ()
 - 方法五 ()
}


'结束
@enduml


